<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ATS.Contracts\ATS.Contracts.csproj" />
    <ProjectReference Include="..\ATS.Domain\ATS.Domain.csproj" />
    <ProjectReference Include="..\ATS.Infrastructure\ATS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
